services:
  web:
    build:
      context: .
      dockerfile: ./web.Dockerfile
      args:
        - PORT=${PORT}
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
  cron:
    build:
      context: .
      dockerfile: ./cron.Dockerfile
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: true
