services:
  web:
    build:
      context: .
      dockerfile: ./web.Dockerfile
      args:
        - PORT=${PORT}
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
    extra_hosts:
      - host.docker.internal:host-gateway
  cron:
    build:
      context: .
      dockerfile: ./cron.Dockerfile
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: true
    extra_hosts:
      - host.docker.internal:host-gateway
  # This is a naive way to do migration on the author's server, but for now it just works :)
  migration:
    build:
      context: .
      dockerfile: ./db.Dockerfile
    env_file:
      - path: ./.env
        required: true
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      web:
        condition: service_healthy
      # TODO: Define the healtcheck for the cron job
      # cron:
      #   condition: service_healthy
